### ISSUE TITLE
Robots

### ISSUE THREAD

**Issue by emaildano** [j2made/gemini#3]
@iamhexcoder 

Should we add a function to use the WP disallow index feature. So it's always set to block robots.

Or should we add a robots.txt to the repo? I'm thinking CMS should never be indexed.

**Comment by baerkins** [comment]
The Gemini version of EVA, [gemini-init.php](https://github.com/j2made/gemini/blob/master/cms/content/mu-plugins/gemini-init.php), turns indexing off on line 55:

```

/**
 * SET SE Indexing to False
 * ------------------------
 * No need for Search Engines to know the CMS exists.
 *
 * @since  1.0.0
 */
add_filter( 'pre_option_blog_public', '__return_false' );
```

**Comment by emaildano** [comment]
:+1:
